FROM nginx
COPY default /etc/nginx/sites-enabled/default
COPY dhparam.pem /etc/ssl/certs/dhparam.pem
COPY nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
COPY ssl-params.conf /etc/nginx/snippets/ssl-params.conf
COPY self-signed.conf /etc/nginx/snippets/self-signed.conf
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 
EXPOSE 443